#datasource config
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        
#eureka config
eureka:
  instance:
    prefer-ip-address: true
  client:
    #bilgilerini eureka sunucusundan alıp almayacağını belirtir.
    fetch-registry: true         # sunucu ile  register-with-eureka: true aynı olmalıdır.
    register-with-eureka: true   #eureka server'a kayıt ol.
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka servis kayıt defterine nasıl bağlanacağını belirtir.

